# Generated by Django 3.2.4 on 2021-06-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='images/beagle.jpg', upload_to='images/'),
        ),
    ]
