# Generated by Django 3.2.4 on 2021-06-30 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='photos.location'),
            preserve_default=False,
        ),
    ]
