# Generated by Django 3.2.4 on 2021-06-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=6),
            preserve_default=False,
        ),
    ]
